version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: maauso/zkui
    hostname: zkui
    ports:
      - 9090:9090
    environment:
      ZKLIST: zookeeper:2181
    depends_on:
      - zookeeper

networks:
  default:
    external:
      name: kafka_cluster