version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka:latest
    deploy:
      mode: replicated
      replicas: 3
      #resources:
      #  limits:
      #    cpus: "0.5"
      #    memory: 1024M
      restart_policy:
        condition: on-failure
#    ports:
#      - target: 908{{.Task.ID}}
#        published: 908{{.Task.ID}}
#        protocol: tcp
#        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1{{.Task.Slot}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - zookeeper

  kafkaoffsetmonitor:
    image: junxy/kafkaoffsetmonitor
    # build: .
    container_name: kafkaoffsetmonitor
    # restart: always
    ports:
      - "8080:8080"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - kafka


networks:
  default:
    external:
      name: kafka_cluster